version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/client-deploy"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:10"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "kivymd"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
